---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Licuadora
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Consola de videojuegos
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Navegador GPS
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Teléfono celular
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una mesa de madera
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Cajero automático
  checked: true
name: "¿Dónde viven las computadoras?"
