---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Resolver ejercicios en Mumuki
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Bajar las fotos de una cámara a una computadora de escritorio con un cable
    USB
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Leer un libro en PDF
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ver una película en un sitio Web
  checked: true
name: "¿Qué es internet?"
