---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una red es una computadora que tiene canciones
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una red es un grupo de computadoras conectadas entre sí
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una red es una conexión entre computadoras
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Una red es una transferencia entre computadoras
  checked: false
name: En red adera
