---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Es imposible
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Utilizando una red LAN
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Conectando redes LAN para crear una red que abarque un área más extensa
  checked: true
name: Local vs. Visitante
