---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Por paloma mensajera
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Por las raíces de los árboles, que son buenas conductoras de información
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Por el aire
  checked: true
name: Globalización y olvidate
